import { requireSupabase } from '../supabaseClient';
import type { GalleryItem, PartnershipRequest, Product, ProductInput, Promotion, PromotionInput, QuoteRequest, QuoteRequestInput, QuoteRequestStatus, Review, Stall, StallInput, User } from '../types';

type DbProfile = { id: string; name: string; email: string; role: 'user' | 'admin' };
type DbProduct = { id: string; name: string; description: string; price: number | string; image_url: string; listing_type?: Product['listingType']; category?: string; price_note?: string; compare_at_price?: number | string | null; is_available?: boolean; featured?: boolean; sort_order?: number };
type DbPromotion = { id: string; title: string; description: string; image_url: string; promotion_label: string; start_at?: string | null; end_at?: string | null; is_active: boolean; sort_order?: number };
type DbGallery = { id: string; type: 'image' | 'video'; url: string; thumbnail_url?: string | null; caption?: string; sort_order?: number };
type DbReview = { id: string; author: string; rating: number; comment: string; created_at: string };
type DbStall = {
  id: string; owner_id: string; name: string; slogan: string; category: string; logo_url: string; banner_url: string; description: string; mission: string;
  address: string; latitude: number | null; longitude: number | null; phone: string; email: string; website: string; whatsapp?: string; instagram?: string; facebook?: string; trading_hours?: string;
  featured: boolean; status: Stall['status']; products?: DbProduct[]; promotions?: DbPromotion[]; gallery_items?: DbGallery[]; reviews?: DbReview[];
};
type DbPartnership = { id: string; proposer_stall_id: string; recipient_stall_id: string; message: string; status: PartnershipRequest['status']; created_at: string };
type DbQuoteRequest = { id: string; stall_id: string; product_id?: string | null; requester_name: string; requester_phone: string; requester_email: string; preferred_contact: QuoteRequest['preferredContact']; message: string; budget_note: string; status: QuoteRequestStatus; created_at: string; products?: { name: string } | null };
export type AdminMfaState = { enrolled: boolean; verified: boolean; factorId?: string };

const stallSelect = '*, products(*), promotions(*), gallery_items(*), reviews(*)';
const toProduct = (row: DbProduct): Product => ({ id: row.id, name: row.name, description: row.description, price: Number(row.price), imageUrl: row.image_url, listingType: row.listing_type ?? 'product', category: row.category ?? '', priceNote: row.price_note ?? '', compareAtPrice: row.compare_at_price == null ? undefined : Number(row.compare_at_price), isAvailable: row.is_available ?? true, featured: row.featured ?? false, sortOrder: row.sort_order ?? 0 });
const toPromotion = (row: DbPromotion): Promotion => ({ id: row.id, title: row.title, description: row.description, imageUrl: row.image_url, promotionLabel: row.promotion_label, startAt: row.start_at ?? undefined, endAt: row.end_at ?? undefined, isActive: row.is_active, sortOrder: row.sort_order ?? 0 });
const toStall = (row: DbStall): Stall => ({
  id: row.id, ownerId: row.owner_id, name: row.name, slogan: row.slogan, category: row.category, logo_url: row.logo_url, banner_url: row.banner_url, description: row.description, mission: row.mission,
  products: (row.products ?? []).map(toProduct).sort((a, b) => Number(b.featured) - Number(a.featured) || a.sortOrder - b.sortOrder),
  promotions: (row.promotions ?? []).map(toPromotion).sort((a, b) => a.sortOrder - b.sortOrder),
  gallery: (row.gallery_items ?? []).map((item): GalleryItem => ({ id: item.id, type: item.type, url: item.url, thumbnailUrl: item.thumbnail_url ?? undefined, caption: item.caption ?? '', sortOrder: item.sort_order ?? 0 })).sort((a, b) => a.sortOrder - b.sortOrder),
  reviews: (row.reviews ?? []).map((review): Review => ({ id: review.id, author: review.author, rating: review.rating, comment: review.comment, date: review.created_at })),
  location: { address: row.address, lat: row.latitude ?? 0, lng: row.longitude ?? 0 }, contact: { phone: row.phone, email: row.email, website: row.website, whatsapp: row.whatsapp ?? '', instagram: row.instagram ?? '', facebook: row.facebook ?? '' }, tradingHours: row.trading_hours ?? '', featured: row.featured, status: row.status,
});

const toUser = async (authUser: { id: string; email?: string } | null): Promise<User | null> => {
  if (!authUser) return null;
  const client = requireSupabase();
  const { data: profile, error } = await client.from('profiles').select('id, name, email, role').eq('id', authUser.id).maybeSingle<DbProfile>(); if (error) throw error;
  const { data: stall, error: stallError } = await client.from('stalls').select('id').eq('owner_id', authUser.id).maybeSingle<{ id: string }>(); if (stallError) throw stallError;
  return { id: authUser.id, email: profile?.email ?? authUser.email, name: profile?.name ?? authUser.email?.split('@')[0] ?? 'Member', role: profile?.role ?? 'user', stallId: stall?.id };
};
const fetchStall = async (id: string): Promise<Stall | null> => { const { data, error } = await requireSupabase().from('stalls').select(stallSelect).eq('id', id).maybeSingle<DbStall>(); if (error) throw error; return data ? toStall(data) : null; };
const toPartnership = async (row: DbPartnership): Promise<PartnershipRequest> => { const [proposerStall, recipientStall] = await Promise.all([fetchStall(row.proposer_stall_id), fetchStall(row.recipient_stall_id)]); return { id: row.id, proposerStallId: row.proposer_stall_id, recipientStallId: row.recipient_stall_id, proposerStall: proposerStall ?? undefined, recipientStall: recipientStall ?? undefined, message: row.message, status: row.status, date: row.created_at }; };
const toQuoteRequest = (row: DbQuoteRequest): QuoteRequest => ({ id: row.id, stallId: row.stall_id, productId: row.product_id ?? undefined, productName: row.products?.name, requesterName: row.requester_name, requesterPhone: row.requester_phone ?? '', requesterEmail: row.requester_email ?? '', preferredContact: row.preferred_contact, message: row.message, budgetNote: row.budget_note ?? '', status: row.status, createdAt: row.created_at });
const quoteRequestPayload = (input: QuoteRequestInput) => ({ requester_name: input.requesterName.trim(), requester_phone: input.requesterPhone.trim(), requester_email: input.requesterEmail.trim(), preferred_contact: input.preferredContact, ...(input.productId && { product_id: input.productId }), message: input.message.trim(), budget_note: input.budgetNote.trim() });
const stallPayload = (stall: Partial<Stall>) => ({
  ...(stall.name !== undefined && { name: stall.name.trim() }), ...(stall.slogan !== undefined && { slogan: stall.slogan.trim() }), ...(stall.category !== undefined && { category: stall.category }), ...(stall.logo_url !== undefined && { logo_url: stall.logo_url.trim() }), ...(stall.banner_url !== undefined && { banner_url: stall.banner_url.trim() }), ...(stall.description !== undefined && { description: stall.description.trim() }), ...(stall.mission !== undefined && { mission: stall.mission.trim() }), ...(stall.location?.address !== undefined && { address: stall.location.address.trim() }), ...(stall.location?.lat !== undefined && { latitude: stall.location.lat }), ...(stall.location?.lng !== undefined && { longitude: stall.location.lng }), ...(stall.contact?.phone !== undefined && { phone: stall.contact.phone.trim() }), ...(stall.contact?.email !== undefined && { email: stall.contact.email.trim() }), ...(stall.contact?.website !== undefined && { website: stall.contact.website.trim() }), ...(stall.contact?.whatsapp !== undefined && { whatsapp: stall.contact.whatsapp.trim() }), ...(stall.contact?.instagram !== undefined && { instagram: stall.contact.instagram.trim() }), ...(stall.contact?.facebook !== undefined && { facebook: stall.contact.facebook.trim() }), ...(stall.tradingHours !== undefined && { trading_hours: stall.tradingHours.trim() }),
});
const productPayload = (product: Partial<Product>) => ({ ...(product.name !== undefined && { name: product.name.trim() }), ...(product.description !== undefined && { description: product.description.trim() }), ...(product.price !== undefined && { price: product.price }), ...(product.imageUrl !== undefined && { image_url: product.imageUrl.trim() }), ...(product.listingType !== undefined && { listing_type: product.listingType }), ...(product.category !== undefined && { category: product.category.trim() }), ...(product.priceNote !== undefined && { price_note: product.priceNote.trim() }), ...(Object.prototype.hasOwnProperty.call(product, 'compareAtPrice') && { compare_at_price: product.compareAtPrice ?? null }), ...(product.isAvailable !== undefined && { is_available: product.isAvailable }), ...(product.featured !== undefined && { featured: product.featured }), ...(product.sortOrder !== undefined && { sort_order: product.sortOrder }) });
const promotionPayload = (promotion: Partial<Promotion>) => ({ ...(promotion.title !== undefined && { title: promotion.title.trim() }), ...(promotion.description !== undefined && { description: promotion.description.trim() }), ...(promotion.imageUrl !== undefined && { image_url: promotion.imageUrl.trim() }), ...(promotion.promotionLabel !== undefined && { promotion_label: promotion.promotionLabel.trim() }), ...(promotion.startAt !== undefined && { start_at: promotion.startAt || null }), ...(promotion.endAt !== undefined && { end_at: promotion.endAt || null }), ...(promotion.isActive !== undefined && { is_active: promotion.isActive }), ...(promotion.sortOrder !== undefined && { sort_order: promotion.sortOrder }) });

export const api = {
  async getAdminMfaState(): Promise<AdminMfaState> { const client = requireSupabase(); const [{ data: assurance, error: assuranceError }, { data: factors, error: factorsError }] = await Promise.all([client.auth.mfa.getAuthenticatorAssuranceLevel(), client.auth.mfa.listFactors()]); if (assuranceError) throw assuranceError; if (factorsError) throw factorsError; const factor = factors.totp.find((item) => item.status === 'verified'); return { enrolled: Boolean(factor), verified: assurance.currentLevel === 'aal2', factorId: factor?.id }; },
  async enrolAdminMfa() { const { data, error } = await requireSupabase().auth.mfa.enroll({ factorType: 'totp', friendlyName: 'Exhistall administrator' }); if (error) throw error; return { factorId: data.id, qrCode: data.totp.qr_code }; },
  async verifyAdminMfa(factorId: string, code: string): Promise<void> { const client = requireSupabase(); const { data: challenge, error: challengeError } = await client.auth.mfa.challenge({ factorId }); if (challengeError) throw challengeError; const { error } = await client.auth.mfa.verify({ factorId, challengeId: challenge.id, code }); if (error) throw error; },
  async getStalls(): Promise<Stall[]> { const { data, error } = await requireSupabase().from('stalls').select(stallSelect).eq('status', 'active').order('featured', { ascending: false }).order('created_at', { ascending: false }); if (error) throw error; return ((data ?? []) as DbStall[]).map(toStall); },
  async getAllStallsForAdmin(): Promise<Stall[]> { const { data, error } = await requireSupabase().from('stalls').select(stallSelect).order('created_at', { ascending: false }); if (error) throw error; return ((data ?? []) as DbStall[]).map(toStall); }, getStallById: fetchStall,
  async login(email: string, password: string): Promise<User | null> { const { data, error } = await requireSupabase().auth.signInWithPassword({ email: email.trim(), password }); if (error) return null; return toUser(data.user); },
  async signUp(name: string, email: string, password: string) { const { data, error } = await requireSupabase().auth.signUp({ email: email.trim(), password, options: { data: { name: name.trim() } } }); if (error) throw error; return { user: data.session ? await toUser(data.user) : null, confirmationRequired: !data.session }; },
  async logout(): Promise<void> { const { error } = await requireSupabase().auth.signOut(); if (error) throw error; }, async getCurrentUser() { const { data, error } = await requireSupabase().auth.getUser(); if (error) return null; return toUser(data.user); },
  async getUsers(): Promise<User[]> { const client = requireSupabase(); const { data: profiles, error } = await client.from('profiles').select('id, name, email, role').order('created_at', { ascending: false }); if (error) throw error; const { data: stalls, error: stallsError } = await client.from('stalls').select('id, owner_id'); if (stallsError) throw stallsError; const stallByOwner = new Map((stalls ?? []).map((stall: { id: string; owner_id: string }) => [stall.owner_id, stall.id])); return ((profiles ?? []) as DbProfile[]).map(profile => ({ ...profile, stallId: stallByOwner.get(profile.id) })); },
  async createStall(stallData: StallInput) { const user = await this.getCurrentUser(); if (!user) throw new Error('Please sign in before creating a stall.'); if (user.stallId) throw new Error('You already have a stall.'); const { data, error } = await requireSupabase().from('stalls').insert({ ...stallPayload(stallData), owner_id: user.id, status: 'pending_review', featured: false }).select(stallSelect).single<DbStall>(); if (error) throw error; return toStall(data); },
  async updateStall(stallId: string, updates: Partial<Stall>) { const { data, error } = await requireSupabase().from('stalls').update(stallPayload(updates)).eq('id', stallId).select(stallSelect).maybeSingle<DbStall>(); if (error) throw error; return data ? toStall(data) : null; },
  async updateStallStatus(stallId: string, status: Stall['status']) { const { data, error } = await requireSupabase().rpc('admin_update_stall_status', { target_stall_id: stallId, next_status: status }); if (error) throw error; return data ? fetchStall(stallId) : null; },
  async proposePartnership(proposerStall: Stall, recipientStall: Stall, message: string) { const { data, error } = await requireSupabase().from('partnership_requests').insert({ proposer_stall_id: proposerStall.id, recipient_stall_id: recipientStall.id, message: message.trim(), status: 'pending' }).select('*').single<DbPartnership>(); if (error) throw error; return toPartnership(data); },
  async getPartnershipRequestsForStall(stallId: string) { const { data, error } = await requireSupabase().from('partnership_requests').select('*').or(`proposer_stall_id.eq.${stallId},recipient_stall_id.eq.${stallId}`).order('created_at', { ascending: false }); if (error) throw error; return Promise.all(((data ?? []) as DbPartnership[]).map(toPartnership)); },
  async updatePartnershipRequestStatus(requestId: string, status: 'accepted' | 'declined') { const { data, error } = await requireSupabase().from('partnership_requests').update({ status }).eq('id', requestId).select('*').maybeSingle<DbPartnership>(); if (error) throw error; return data ? toPartnership(data) : null; },
  async addGalleryItem(stallId: string, url: string) { const { error } = await requireSupabase().from('gallery_items').insert({ stall_id: stallId, type: 'image', url: url.trim() }); if (error) throw error; return fetchStall(stallId); }, async deleteGalleryItem(stallId: string, galleryItemId: string) { const { error } = await requireSupabase().from('gallery_items').delete().eq('id', galleryItemId).eq('stall_id', stallId); if (error) throw error; return fetchStall(stallId); },
  async addProduct(stallId: string, productData: ProductInput) { const { error } = await requireSupabase().from('products').insert({ stall_id: stallId, ...productPayload(productData) }); if (error) throw error; return fetchStall(stallId); }, async updateProduct(stallId: string, productId: string, updates: Partial<Product>) { const { error } = await requireSupabase().from('products').update(productPayload(updates)).eq('id', productId).eq('stall_id', stallId); if (error) throw error; return fetchStall(stallId); }, async deleteProduct(stallId: string, productId: string) { const { error } = await requireSupabase().from('products').delete().eq('id', productId).eq('stall_id', stallId); if (error) throw error; return fetchStall(stallId); },
  async addPromotion(stallId: string, promotionData: PromotionInput) { const { error } = await requireSupabase().from('promotions').insert({ stall_id: stallId, ...promotionPayload(promotionData) }); if (error) throw error; return fetchStall(stallId); }, async updatePromotion(stallId: string, promotionId: string, updates: Partial<Promotion>) { const { error } = await requireSupabase().from('promotions').update(promotionPayload(updates)).eq('id', promotionId).eq('stall_id', stallId); if (error) throw error; return fetchStall(stallId); }, async deletePromotion(stallId: string, promotionId: string) { const { error } = await requireSupabase().from('promotions').delete().eq('id', promotionId).eq('stall_id', stallId); if (error) throw error; return fetchStall(stallId); },
  async createQuoteRequest(stallId: string, input: QuoteRequestInput): Promise<void> { const { error } = await requireSupabase().from('quote_requests').insert({ stall_id: stallId, ...quoteRequestPayload(input) }); if (error) throw error; },
  async getQuoteRequestsForStall(stallId: string) { const { data, error } = await requireSupabase().from('quote_requests').select('*, products(name)').eq('stall_id', stallId).order('created_at', { ascending: false }); if (error) throw error; return ((data ?? []) as DbQuoteRequest[]).map(toQuoteRequest); },
  async updateQuoteRequestStatus(requestId: string, status: QuoteRequestStatus) { const { data, error } = await requireSupabase().from('quote_requests').update({ status }).eq('id', requestId).select('*, products(name)').maybeSingle<DbQuoteRequest>(); if (error) throw error; return data ? toQuoteRequest(data) : null; },
};
