import React from 'react';
import type { QuoteRequest, QuoteRequestStatus } from '../types';
import { Icon } from './Icon';

interface Props { requests: QuoteRequest[]; onUpdateStatus: (id: string, status: QuoteRequestStatus) => Promise<void>; isSaving: boolean; }
const statusStyle: Record<QuoteRequestStatus, string> = { new: 'bg-amber-100 text-amber-800', replied: 'bg-blue-100 text-blue-800', closed: 'bg-slate-200 text-slate-700' };
const contactLabel: Record<QuoteRequest['preferredContact'], string> = { whatsapp: 'WhatsApp', phone: 'Phone call', email: 'Email' };
const QuoteRequestInbox: React.FC<Props> = ({ requests, onUpdateStatus, isSaving }) => {
  const sorted = [...requests].sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt));
  return <div className="space-y-5"><div className="rounded-lg bg-white p-6 shadow-lg dark:bg-slate-800"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#b84c32]">Private buyer enquiries</p><h2 className="mt-1 text-2xl font-bold">Quote requests</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-brand-secondary dark:text-slate-300">These are requests sent directly from your public stall. Reply using the buyer’s preferred contact method, then update the status here so nothing slips through the cracks.</p></div>{!sorted.length ? <div className="rounded-lg bg-white p-10 text-center shadow-lg dark:bg-slate-800"><Icon name="message" className="mx-auto h-10 w-10 text-[#b84c32]" /><h3 className="mt-3 text-xl font-bold">No quote requests yet</h3><p className="mt-2 text-sm text-brand-secondary dark:text-slate-400">Visitors will see a “Request a quote” button on your live stall page.</p></div> : sorted.map((request) => <article key={request.id} className="rounded-lg bg-white p-6 shadow-lg dark:bg-slate-800"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-extrabold">{request.requesterName}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-extrabold capitalize ${statusStyle[request.status]}`}>{request.status}</span></div><p className="mt-1 text-xs text-slate-500">Received {new Date(request.createdAt).toLocaleString()}</p></div><select aria-label="Quote request status" disabled={isSaving} value={request.status} onChange={(event) => onUpdateStatus(request.id, event.target.value as QuoteRequestStatus)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-bold dark:border-slate-600 dark:bg-slate-900"><option value="new">New</option><option value="replied">Replied</option><option value="closed">Closed</option></select></div>{request.productName && <p className="mt-4 inline-flex rounded-full bg-[#f3dfbb] px-3 py-1 text-sm font-bold text-brand-blue">About: {request.productName}</p>}<p className="mt-4 whitespace-pre-wrap leading-relaxed text-brand-secondary dark:text-slate-200">{request.message}</p>{request.budgetNote && <p className="mt-3 rounded-md bg-slate-50 p-3 text-sm dark:bg-slate-700/50"><strong>Budget or timing:</strong> {request.budgetNote}</p>}<div className="mt-5 grid gap-3 border-t pt-4 text-sm sm:grid-cols-2 dark:border-slate-700"><p><strong>Preferred reply:</strong> {contactLabel[request.preferredContact]}</p>{request.requesterPhone && <a className="font-bold text-brand-blue hover:underline dark:text-brand-gold" href={`tel:${request.requesterPhone}`}>{request.requesterPhone}</a>}{request.requesterEmail && <a className="font-bold text-brand-blue hover:underline dark:text-brand-gold" href={`mailto:${request.requesterEmail}`}>{request.requesterEmail}</a>}</div></article>)}</div>;
};
export default QuoteRequestInbox;
