import React, { useState } from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import StallForm from '../components/StallForm';
import ProductForm from '../components/ProductForm';
import PartnershipRequestCard from '../components/PartnershipRequestCard';
import GalleryManager from '../components/GalleryManager';
import PromotionManager from '../components/PromotionManager';
import { Icon } from '../components/Icon';
import type { Stall, StallInput, PartnershipRequest, User, Product, ProductInput, GalleryItem, Promotion, PromotionInput } from '../types';

interface StallholderDashboardPageProps {
  stall: Stall; partnershipRequests: PartnershipRequest[]; onNavigate: (page: string) => void; currentUser: User; onLogout: () => void; onSearch: (query: string) => void;
  onUpdateStall: (stallId: string, updates: Partial<Stall>) => Promise<void>; onAddProduct: (stallId: string, productData: ProductInput) => Promise<void>; onUpdateProduct: (stallId: string, productId: string, updates: Partial<Product>) => Promise<void>; onDeleteProduct: (stallId: string, productId: string) => Promise<void>;
  onAddPromotion: (stallId: string, promotionData: PromotionInput) => Promise<void>; onUpdatePromotion: (stallId: string, promotionId: string, updates: Partial<Promotion>) => Promise<void>; onDeletePromotion: (stallId: string, promotionId: string) => Promise<void>;
  onAddGalleryItem: (stallId: string, url: string) => Promise<void>; onDeleteGalleryItem: (stallId: string, item: GalleryItem) => Promise<void>; onUpdatePartnershipStatus: (requestId: string, status: 'accepted' | 'declined') => Promise<void>;
}
const StatCard: React.FC<{ title: string; value: string; icon: string }> = ({ title, value, icon }) => <div className="rounded-lg bg-white p-6 shadow-md dark:bg-slate-800"><div className="flex items-center"><div className="rounded-full bg-brand-blue/10 p-3 dark:bg-brand-gold/10"><Icon name={icon} className="h-6 w-6 text-brand-blue dark:text-brand-gold" /></div><div className="ml-4"><p className="text-sm font-medium text-brand-secondary dark:text-slate-400">{title}</p><p className="text-2xl font-bold text-brand-dark dark:text-white">{value}</p></div></div></div>;
type ProductModalState = { isOpen: boolean; mode: 'add' | 'edit'; product: Product | null };

const StallholderDashboardPage: React.FC<StallholderDashboardPageProps> = (props) => {
  const { stall, partnershipRequests, onNavigate, currentUser, onLogout, onSearch, onUpdateStall, onAddProduct, onUpdateProduct, onDeleteProduct, onAddPromotion, onUpdatePromotion, onDeletePromotion, onAddGalleryItem, onDeleteGalleryItem, onUpdatePartnershipStatus } = props;
  const [activeTab, setActiveTab] = useState('overview'); const [isSaving, setIsSaving] = useState(false); const [actionError, setActionError] = useState(''); const [productModal, setProductModal] = useState<ProductModalState>({ isOpen: false, mode: 'add', product: null });
  const runAction = async (action: () => Promise<void>, fallback: string) => { setIsSaving(true); setActionError(''); try { await action(); } catch (error) { setActionError(error instanceof Error ? error.message : fallback); throw error; } finally { setIsSaving(false); } };
  const handleStallUpdate = async (formData: StallInput) => { await runAction(async () => { await onUpdateStall(stall.id, formData); setActiveTab('overview'); }, 'We could not update your stall. Please try again.'); };
  const handleProductSubmit = async (productData: ProductInput) => { await runAction(async () => { if (productModal.mode === 'add') await onAddProduct(stall.id, productData); else if (productModal.product) await onUpdateProduct(stall.id, productModal.product.id, productData); setProductModal({ isOpen: false, mode: 'add', product: null }); }, 'We could not save this listing. Please try again.'); };
  const handleDeleteProductClick = async (productId: string) => { if (window.confirm('Delete this listing? This cannot be undone.')) await runAction(() => onDeleteProduct(stall.id, productId), 'We could not delete this listing. Please try again.'); };
  const handleAddGalleryItem = (url: string) => runAction(() => onAddGalleryItem(stall.id, url), 'We could not add this gallery image. Please try again.');
  const handleDeleteGalleryItem = async (item: GalleryItem) => { if (window.confirm('Remove this image from your gallery?')) await runAction(() => onDeleteGalleryItem(stall.id, item), 'We could not remove this gallery image. Please try again.'); };
  const handleAddPromotion = (input: PromotionInput) => runAction(() => onAddPromotion(stall.id, input), 'We could not save this special. Please try again.');
  const handleUpdatePromotion = (id: string, input: PromotionInput) => runAction(() => onUpdatePromotion(stall.id, id, input), 'We could not update this special. Please try again.');
  const handleDeletePromotion = (id: string) => runAction(() => onDeletePromotion(stall.id, id), 'We could not delete this special. Please try again.');
  const incomingRequests = partnershipRequests.filter((request) => request.recipientStallId === stall.id); const outgoingRequests = partnershipRequests.filter((request) => request.proposerStallId === stall.id);
  const totalListings = stall.products.length; const activeListings = stall.products.filter((item) => item.isAvailable !== false).length; const serviceCount = stall.products.filter((item) => item.listingType === 'service').length;
  const readinessItems = [{ label: 'Stall name and category', done: Boolean(stall.name && stall.category) }, { label: 'A clear business story', done: Boolean(stall.description) }, { label: 'At least one way to contact you', done: Boolean(stall.contact.phone || stall.contact.email || stall.contact.website || stall.contact.whatsapp) }, { label: 'A banner or logo', done: Boolean(stall.logo_url || stall.banner_url) }, { label: 'A live catalogue listing', done: activeListings > 0 }, { label: 'At least three gallery images', done: stall.gallery.length >= 3 }];
  const readyCount = readinessItems.filter((item) => item.done).length;
  const statusChip = stall.status === 'active' ? <span className="rounded-full bg-green-100 px-3 py-1 text-sm font-semibold text-green-700 dark:bg-green-900 dark:text-green-300">Live</span> : stall.status === 'pending_review' ? <span className="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700 dark:bg-blue-900 dark:text-blue-300">Pending review</span> : <span className="rounded-full bg-yellow-100 px-3 py-1 text-sm font-semibold text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300">{stall.status}</span>;
  const renderTabContent = () => {
    if (activeTab === 'edit-stall') return <div className="rounded-lg bg-white p-8 shadow-lg dark:bg-slate-800"><h2 className="mb-2 text-2xl font-bold">Build your stallfront</h2><p className="mb-6 text-sm text-brand-secondary dark:text-slate-400">These details help a visitor understand who you are and how to reach you.</p><StallForm stall={stall} onSubmit={handleStallUpdate} onCancel={() => setActiveTab('overview')} isSaving={isSaving} /></div>;
    if (activeTab === 'manage-products') return <div className="rounded-lg bg-white p-6 shadow-lg dark:bg-slate-800"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">Catalogue</h2><p className="mt-1 text-sm text-brand-secondary dark:text-slate-400">Products and services share one neat, visitor-friendly counter.</p></div><button onClick={() => { setActionError(''); setProductModal({ isOpen: true, mode: 'add', product: null }); }} className="inline-flex items-center gap-2 rounded-lg bg-brand-blue px-4 py-2 font-bold text-white"><Icon name="plus-circle" className="h-5 w-5" />Add listing</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase text-gray-700 dark:bg-gray-700 dark:text-gray-400"><tr><th className="px-4 py-3">Listing</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Visibility</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{stall.products.map((product) => <tr key={product.id} className="border-b dark:border-gray-700"><th className="px-4 py-4 font-medium text-gray-900 dark:text-white">{product.name}{product.featured && <span className="ml-2 rounded-full bg-amber-100 px-2 py-1 text-xs text-amber-800">Featured</span>}</th><td className="px-4 py-4 capitalize">{product.listingType ?? 'product'}</td><td className="px-4 py-4">R {product.price.toFixed(2)}</td><td className="px-4 py-4"><span className={product.isAvailable !== false ? 'font-semibold text-green-700 dark:text-green-300' : 'font-semibold text-slate-500'}>{product.isAvailable !== false ? 'Visible' : 'Hidden'}</span></td><td className="flex gap-4 px-4 py-4"><button onClick={() => { setActionError(''); setProductModal({ isOpen: true, mode: 'edit', product }); }} className="font-medium text-brand-blue hover:underline dark:text-brand-gold">Edit</button><button onClick={() => handleDeleteProductClick(product.id)} className="font-medium text-red-600 hover:underline">Delete</button></td></tr>)}</tbody></table>{!totalListings && <p className="py-8 text-center text-brand-secondary dark:text-slate-400">Start with your best product or service. You can add more anytime.</p>}</div></div>;
    if (activeTab === 'specials') return <PromotionManager promotions={stall.promotions ?? []} onAdd={handleAddPromotion} onUpdate={handleUpdatePromotion} onDelete={handleDeletePromotion} isSaving={isSaving} />;
    if (activeTab === 'manage-gallery') return <GalleryManager gallery={stall.gallery} onAdd={handleAddGalleryItem} onDelete={handleDeleteGalleryItem} isSaving={isSaving} />;
    if (activeTab === 'partnerships') return <div><h2 className="mb-6 text-2xl font-bold">Partnership requests</h2><div className="grid gap-8 md:grid-cols-2"><div><h3 className="mb-4 text-lg font-semibold">Incoming ({incomingRequests.length})</h3><div className="space-y-4">{incomingRequests.map((request) => <PartnershipRequestCard key={request.id} request={request} perspective="incoming" onUpdateStatus={onUpdatePartnershipStatus} />)}{!incomingRequests.length && <p className="text-sm text-brand-secondary dark:text-slate-400">No incoming partnership requests.</p>}</div></div><div><h3 className="mb-4 text-lg font-semibold">Outgoing ({outgoingRequests.length})</h3><div className="space-y-4">{outgoingRequests.map((request) => <PartnershipRequestCard key={request.id} request={request} perspective="outgoing" />)}{!outgoingRequests.length && <p className="text-sm text-brand-secondary dark:text-slate-400">You have not sent any partnership requests.</p>}</div></div></div></div>;
    return <div className="space-y-8"><div className="grid grid-cols-1 gap-6 md:grid-cols-3"><StatCard title="Live listings" value={`${activeListings}/${totalListings}`} icon="package" /><StatCard title="Services" value={serviceCount.toString()} icon="briefcase" /><StatCard title="Specials" value={(stall.promotions ?? []).filter((promotion) => promotion.isActive).length.toString()} icon="ticket" /></div><section className="rounded-lg bg-white p-8 shadow-lg dark:bg-slate-800"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">Stall status</h2><p className="mt-2 text-brand-secondary dark:text-slate-300">{stall.status === 'pending_review' ? 'Your stall is private while it is reviewed. Keep preparing it — all changes will be ready for approval.' : stall.status === 'active' ? 'Your stall is live in the marketplace. Keep its catalogue and contact details current.' : 'Your stall is currently not publicly visible.'}</p></div>{statusChip}</div></section><section className="rounded-lg bg-white p-8 shadow-lg dark:bg-slate-800"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Visitor readiness</h2><p className="mt-1 text-sm text-brand-secondary dark:text-slate-400">{readyCount} of {readinessItems.length} essentials are in place.</p></div><button type="button" onClick={() => setActiveTab('edit-stall')} className="font-bold text-brand-blue hover:underline dark:text-brand-gold">Improve stall details</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{readinessItems.map((item) => <div key={item.label} className="flex items-center gap-3 rounded-md bg-brand-light p-3 dark:bg-slate-700/40"><Icon name={item.done ? 'check-circle' : 'arrow-right'} className={`h-5 w-5 ${item.done ? 'text-green-600' : 'text-[#b84c32]'}`} /><span className={item.done ? 'font-semibold' : ''}>{item.label}</span></div>)}</div></section></div>;
  };
  const tabs = [{ id: 'overview', label: 'Overview', icon: 'dashboard' }, { id: 'edit-stall', label: 'Stallfront', icon: 'edit' }, { id: 'manage-products', label: 'Catalogue', icon: 'package' }, { id: 'specials', label: 'Specials', icon: 'ticket' }, { id: 'manage-gallery', label: 'Gallery', icon: 'upload' }, { id: 'partnerships', label: 'Partnerships', icon: 'briefcase' }];
  return <><Header onNavigate={onNavigate} currentUser={currentUser} onLogout={onLogout} onSearch={onSearch} /><main className="bg-brand-light dark:bg-brand-dark"><div className="container mx-auto px-4 py-12 sm:px-6 lg:px-8"><h1 className="mb-2 text-3xl font-extrabold">My stall workspace</h1><p className="mb-8 text-brand-secondary dark:text-slate-400">Keep your exhibition ready for the people you want to meet.</p><div className="grid gap-8 lg:grid-cols-4"><aside className="lg:col-span-1"><div className="sticky top-24 rounded-lg bg-white p-4 shadow-lg dark:bg-slate-800"><nav className="flex flex-col gap-2">{tabs.map((tab) => <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex w-full items-center gap-3 rounded-md p-3 text-left text-sm font-semibold transition-colors ${activeTab === tab.id ? 'bg-brand-blue/10 text-brand-blue dark:bg-brand-gold/20 dark:text-brand-gold' : 'hover:bg-gray-100 dark:hover:bg-slate-700/50'}`}><Icon name={tab.icon} className="h-5 w-5" /><span>{tab.label}</span></button>)}</nav></div></aside><div className="lg:col-span-3">{actionError && <p role="alert" className="mb-6 rounded-md bg-red-50 p-4 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-300">{actionError}</p>}{renderTabContent()}</div></div></div></main><Footer onNavigate={onNavigate} />{productModal.isOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-lg bg-white shadow-xl dark:bg-slate-800"><div className="p-6"><div className="mb-4 flex items-center justify-between"><h3 className="text-xl font-bold">{productModal.mode === 'add' ? 'Add a catalogue listing' : 'Edit catalogue listing'}</h3><button onClick={() => setProductModal({ isOpen: false, mode: 'add', product: null })} className="rounded-full p-1 hover:bg-gray-200 dark:hover:bg-slate-700"><Icon name="x" className="h-5 w-5" /></button></div><ProductForm product={productModal.product} onSubmit={handleProductSubmit} onCancel={() => setProductModal({ isOpen: false, mode: 'add', product: null })} isSaving={isSaving} /></div></div></div>}</>;
};
export default StallholderDashboardPage;
